Kucoin/kucoin-api-docs

source/localizable/index.cn.html.md
source/localizable/index.html.md

Fixed description for Limit order parameters

Fixed description for Limit order parameters

---

examples/php/singleDemo.php
source/localizable/index.cn.html.md
source/localizable/index.html.md

Add connection limit description for websocket
Update List Fills time range from 24 hours to one week
Add methods to singleDemo.php

 Update List Fills time range from 24 hours to one week

---

source/localizable/index.html.md

修改一些错误、新增私有频道订阅

---

source/stylesheets/screen.css.scss

解决锚点定位不准的问题

---

source/localizable/index.html.md

修改私有频道订阅说明文案

---

source/localizable/index.html.md

修改acceptUsermessage描述

---

source/localizable/index.html.md

增加了cancel订单只保留一个月的说法，增加了Ledgers中biztype枚举类型

增加了cancel订单只保留一个月的说法，增加了Ledgers中biztype枚举类型

---

source/localizable/index.html.md

介绍中增加了如何划转资产的引导

---

source/localizable/index.html.md

修改inner transfer单词错误

---

source/localizable/index.html.md

增加创建账户说明、增加撮合引擎和下单系统时间使用说明

---

source/localizable/index.html.md

增加下单系统和撮合引擎使用纳秒时间的说法

---

source/localizable/index.html.md

增加timestamp中订单和撮合引擎使用纳秒的描述

---

source/javascripts/app/_toc.js
source/localizable/index.html.md

修改锚点不准确问题、增加了volValue的注释

---

source/localizable/index.html.md

增加了历史查询数据接口默认查询一个月限定的说法

---

source/localizable/index.html.md

修改做市商计划、新增VIP

---

source/localizable/index.html.md

修改单用户单交易对下单数量为200

---

source/localizable/index.html.md

修改websocket创建路径

---

source/localizable/index.html.md

symbols接口增加feeCurrency字段，对L3的订阅增加说明、增加如何维护L3 orderbook

symbols接口增加feeCurrency字段，对L3的订阅增加说明、增加如何维护L3 orderbook

---

source/localizable/index.html.md

增加takerOrderId在match中的描述

---

source/localizable/index.html.md

修改冰山委托和隐藏委托说明

---

source/localizable/index.html.md

修改冰山单和隐藏单说明

---

source/localizable/index.html.md

增加币种获取法币的说明

---

source/localizable/index.html.md

增加子母账户划转提示

---

source/localizable/index.html.md

删除V1提币remark返回字段

---

source/localizable/index.html.md

修改V1充提接口返回无效字段

---

source/localizable/index.html.md

增加chain字段、增加划转描述

---

source/localizable/index.html.md

增加了chain的说明

---

source/localizable/index.html.md

修改限频策略、增加L3演示demo、修改部分描述问题

---

source/localizable/index.html.md

优化list json格式

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Modify the 'Transfer between Master user and Sub-user ' endpoint, which will be effective TOMORROW, pls change your request params, THX.

Modify the 'Transfer between Master user and Sub-user ' endpoint

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

在 Get All tickers接口中新增symbolName字段，用于外部显示

在 Get All tickers接口中新增symbolName字段，用于外部显示

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

在 Get All tickers接口中新增symbolName字段，用于第三方调用显示

在 Get All tickers接口中新增symbolName字段，用于第三方调用显示

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

合并ETH、NEO、TRX交易市场为ALTS

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Modify translation;
Replace the level-3 demo link;
Modify threshold price;

Proofreading

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Modify the request parameter time range of Get Account Ledgers.

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Check and revise the document description to improve the readability of the document

Check and revise the document description to improve the readability of the document

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

- Add [Get Currency Detail(Recommend)](#get-currency-detail-recommend) endpoint.
- Modify [List of currently supported symbol](#list-of-currently-supported-symbol) by Index Price and Mark Price for Margin.

Add Get Currency Detail(Recommend) endpoint. Modify List of currently supported symbol by Index Price and Mark Price for Margin.

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Add the following interfaces related to sub-account: `GET /api/v1/user-info`、`POST /api/v1/sub/user`、`GET /api/v1/sub/api-key`、`POST /api/v1/sub/api-key`、`POST /v1/sub/api-key/update`、`DELETE /api/v1/sub/api-key`

Add the following interfaces related to sub-account

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

- Add `chain` response field to `GET /api/v1/withdrawals` interface  and `GET /api/v1/deposits` interface
- Add `generalSubQuantity`, `marginSubQuantity`, `futuresSubQuantity`, `maxDefaultSubQuantity`, `maxGeneralSubQuantity`, `maxMarginSubQuantity` and `maxFuturesSubQuantity` fields to `POST /api/v1/sub/user` interface response
- Add `GET /api/v2/sub/user` and `GET /api/v2/sub-accounts` pagination interface

Sub-account related interface and withdrawal interface change

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

status接口描述優化

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Add API Expire Time

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

change websocket endpoint

---

source/localizable/index.cn.html.md
source/localizable/index.html.md

Authority optimization
